<?php

class HomeController extends BaseController
{
    function onInit()
    {
        parent::onInit(); // TODO: Change the autogenerated stub
        $this->model = new PostsModel();
    }

    function index()
    {
        $this-> posts = $this->model->getAll(1, 3);
    }

    function view($id)
    {
        // TODO: Load a post to be displayed here ...
        $this->post = $this->model-> getPostById($id);
    }
}
